### ISSUE TITLE
Adding documentation

### ISSUE THREAD

**Issue by iamgp** [maddhatter/laravel-fullcalendar#12]
Your documentation is confusing.

"Events" can be confused with Laravel Events.
You call models interfaces.

The documentation as a whole does not take you from start to finish. E.g., perhaps include a sample migration to make the `event_models` table:

```php
class CreateEventModelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('event_models', function (Blueprint $table) {
          $table->increments('id');
          $table->string('title');
          $table->boolean('all_day');
          $table->datetime('start');
          $table->datetime('end');
          $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
      Schema::drop('event_models');
    }
}

```

**Comment by maddhatter** [comment]
Not sure where I call a model an interface. Have an example?

Not really sure what else to call a calendar event other than "event".

I don't feel the example migration is necessary, since it could suggest that particular table structure is required, even tho it isn't. The class implementing `Event` doesn't even need to be a model, it could be anything that you want to represent on a calendar, like the simple DTO objects that are available.
